# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvisUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VoiceAssistant(object):
    def setupUi(self, VoiceAssistant):
        VoiceAssistant.setObjectName("VoiceAssistant")
        VoiceAssistant.resize(1102, 740)
        self.centralwidget = QtWidgets.QWidget(VoiceAssistant)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -40, 1101, 781))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../Jarvis images/gif 3.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 620, 231, 71))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../Jarvis images/bar (2).jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(790, 620, 241, 71))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../Jarvis images/bar (2).jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(80, 630, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(820, 630, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        VoiceAssistant.setCentralWidget(self.centralwidget)

        self.retranslateUi(VoiceAssistant)
        QtCore.QMetaObject.connectSlotsByName(VoiceAssistant)

    def retranslateUi(self, VoiceAssistant):
        _translate = QtCore.QCoreApplication.translate
        VoiceAssistant.setWindowTitle(_translate("VoiceAssistant", "MainWindow"))
        self.pushButton.setText(_translate("VoiceAssistant", "START"))
        self.pushButton_2.setText(_translate("VoiceAssistant", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VoiceAssistant = QtWidgets.QMainWindow()
    ui = Ui_VoiceAssistant()
    ui.setupUi(VoiceAssistant)
    VoiceAssistant.show()
    sys.exit(app.exec_())


